# fly.toml app configuration file generated for personal-assistant on 2024-01-25T16:39:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-assistant"
primary_region = "waw"
console_command = "/code/manage.py shell"

[build]

[deploy]

[env]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
